### ISSUE TITLE
Dataset download link broken

### ISSUE THREAD

**Issue by ueberf** [trisha025/Photozilla#2]
I wanted to take a look a the dataset you created, but the mentioned download link (https://sutdapac-my.sharepoint.com/:f:/g/personal/trisha_singhal_sutd_edu_sg/EqS3NL3qwYNMglM8cQFOmnYB4zOqURLmOcqAisj7MKvG2Q?e=8rQfGj) throws a 404 error.

Any chance of rehosting the dataset?

Thanks!

**Comment by michael-gc** [comment]
Same issue~
Looking forward to accessing the dataset. 

Thanks!

**Comment by JelenaCuka** [comment]
Looks like download link is still broken.

**Comment by sakibnaz** [comment]
Dataset download still not accessible. Any update please?

**Comment by marvin-Yu** [comment]
Hi @trisha025, is there any plan to recover this broken link?

**Comment by trisha025** [comment]
Hi all, sorry for the inconvenience caused.
The dataset link is being fixed. Thanks!

**Comment by trisha025** [comment]
> I wanted to take a look a the dataset you created, but the mentioned download link (https://sutdapac-my.sharepoint.com/:f:/g/personal/trisha_singhal_sutd_edu_sg/EqS3NL3qwYNMglM8cQFOmnYB4zOqURLmOcqAisj7MKvG2Q?e=8rQfGj) throws a 404 error.
> 
> Any chance of rehosting the dataset?
> 
> Thanks!

Sorry for the inconvenience caused.
The dataset link is being fixed. Thanks!

**Comment by trisha025** [comment]
> Same issue~ Looking forward to accessing the dataset.
> 
> Thanks!

Sorry for the inconvenience caused.
The dataset link is being fixed. Thanks!

**Comment by trisha025** [comment]
> Looks like download link is still broken.

Sorry for the inconvenience caused.
The dataset link is being fixed. Thanks!

**Comment by trisha025** [comment]
> Dataset download still not accessible. Any update please?

Sorry for the inconvenience caused.
The dataset link is being fixed. Thanks!

**Comment by trisha025** [comment]
> Hi @trisha025, is there any plan to recover this broken link?

Sorry for the inconvenience caused.
The dataset link is being fixed. Thanks!
